language: node_js
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
after_success:
  - nyc report --reporter=text-lcov | node_modules/.bin/coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
dist: trusty
sudo: false
script: npm run test:coverage
cache:
  directories:
    - ~/.npm
    - node_modules
